CREATE TABLE IF NOT EXISTS client(
    id IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,

    CONSTRAINT CLIENT_NAME_LIMIT CHECK(CHAR_LENGTH(name) BETWEEN 3 AND 200)
);

CREATE TABLE IF NOT EXISTS planet(
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    name VARCHAR(500) NOT NULL,

    CONSTRAINT PLANET_NAME_LIMIT CHECK(CHAR_LENGTH(name) BETWEEN 1 AND 100),
    CONSTRAINT PLANET_ID_LIMIT CHECK(CHAR_LENGTH(name) BETWEEN 1 AND 500),
    CONSTRAINT PLANET_ID_FORMAT CHECK(id REGEXP '^[A-Z0-9]+$')
);

CREATE TABLE IF NOT EXISTS ticket(
    id IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    client_id BIGINT NOT NULL,
    from_planet_id VARCHAR(100) NOT NULL,
    to_planet_id VARCHAR(100) NOT NULL,

    CONSTRAINT TICKET_CLIENT_ID_FK FOREIGN KEY (client_id) REFERENCES client(id),
    CONSTRAINT TICKET_FROM_PLANET_ID_FK FOREIGN KEY (from_planet_id) REFERENCES planet(id),
    CONSTRAINT TICKET_TO_PLANET_ID_FK FOREIGN KEY (to_planet_id) REFERENCES planet(id)
);